// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWyM8YX9PGmvWq-6yteoO7_7tRFxEjVgE',
    appId: '1:356631259820:web:38b925e500182414890d09',
    messagingSenderId: '356631259820',
    projectId: 'yeyo-1725c',
    authDomain: 'yeyo-1725c.firebaseapp.com',
    storageBucket: 'yeyo-1725c.firebasestorage.app',
    measurementId: 'G-E8SW8ZGWN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSn-AwHuRsiCDtpyYTMCvXlo3j4B8QdRg',
    appId: '1:356631259820:android:dd779e695590a196890d09',
    messagingSenderId: '356631259820',
    projectId: 'yeyo-1725c',
    storageBucket: 'yeyo-1725c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFEpI4MUxOvY1KvwNzwzJTnS5OMnL-bUE',
    appId: '1:356631259820:ios:4787e2d62b0572c6890d09',
    messagingSenderId: '356631259820',
    projectId: 'yeyo-1725c',
    storageBucket: 'yeyo-1725c.firebasestorage.app',
    iosBundleId: 'com.example.yeyoQrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFEpI4MUxOvY1KvwNzwzJTnS5OMnL-bUE',
    appId: '1:356631259820:ios:4787e2d62b0572c6890d09',
    messagingSenderId: '356631259820',
    projectId: 'yeyo-1725c',
    storageBucket: 'yeyo-1725c.firebasestorage.app',
    iosBundleId: 'com.example.yeyoQrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWyM8YX9PGmvWq-6yteoO7_7tRFxEjVgE',
    appId: '1:356631259820:web:2b803ea729c9c841890d09',
    messagingSenderId: '356631259820',
    projectId: 'yeyo-1725c',
    authDomain: 'yeyo-1725c.firebaseapp.com',
    storageBucket: 'yeyo-1725c.firebasestorage.app',
    measurementId: 'G-H7M6GTGRXR',
  );
}
